1. Introduction to NumPy and Array Creation

In [1]:
import numpy as np
#creating 1D array with given element
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [2]:
#creating a 2D array with (2,3) shape with all zeros
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
#using linspace to create an evenly spaced array from 0 to 100
a = np.linspace(0,100,5)
a

array([  0.,  25.,  50.,  75., 100.])

2. Array Indexing and Slicing

In [4]:
a = np.array([5, 10, 15, 20, 25, 30])
#extracting first three elements in an array using slicing
b = a[:3]
b

array([ 5, 10, 15])

In [5]:
#extracting every second element from first index
c = a[::2]
#extracting every second element from second index
d= a[1::2]
print(c)
print(d)

[ 5 15 25]
[10 20 30]


In [6]:
#mutating the 4th element to 50 and printing the updated array
a[3] = 50
a

array([ 5, 10, 15, 50, 25, 30])

3. Reshaping Arrays

In [7]:
#creating an 1D array ranging from 1 to 12
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
#reshaping the 1D array into a 2D array of shape (3,4)
b = a.reshape((3,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

4. Broadcasting and Element-wise Operations

In [9]:
# creating a 1D array with given elements
a = np.array([1, 2, 3, 4, 5])
#adding 10 to every element of the array
b = a + 10
b

array([11, 12, 13, 14, 15])

In [10]:
#multiplying each element by 3 of the original array
c = a*3
c

array([ 3,  6,  9, 12, 15])

In [11]:
#calculating the square of each element
d = a**2
d

array([ 1,  4,  9, 16, 25])

5. Basic Statistics with Arrays

In [12]:
a = np.array( [30, 32, 31, 29, 28, 33, 34])
#finding the mean temperature of the week using np.mean
np.mean(a)

31.0

In [13]:
#printing the max and min temperature using the max and min
print(np.max(a))
print(np.min(a))

34
28


In [14]:
#calculating the sum of the temperatures
np.sum(a)

217

6. Real-World Problem: Sales Analysis

In [15]:

a = np.array(([[200, 220, 250, 270, 300],
               [150, 160, 170, 180, 200]]))
total = np.sum(a,axis=1)
#total sales of the two products
total

array([1240,  860])

In [16]:
#average sales per day
average_sales =  np.mean(a,axis = 0)
average_sales

array([175., 190., 210., 225., 250.])

In [17]:
#Highest sales of each product by day
higest_sales_day = np.argmax(a,axis = 1) + 1
higest_sales_day

array([5, 5], dtype=int64)